# Generated by Django 3.0.7 on 2021-06-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210601_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo1',
            new_name='car_photo_1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo2',
            new_name='car_photo_2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo3',
            new_name='car_photo_3',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo4',
            new_name='car_photo_4',
        ),
    ]
